import type { ColumnConfig, DataRow } from "@/types/table-types";

export interface TableTemplate {
	name: string;
	description: string;
	columns: ColumnConfig[];
	sampleData?: DataRow[];
}

export const tableTemplates: Record<string, TableTemplate> = {
	userTable: {
		name: "User Management",
		description: "A table for managing user accounts with basic information",
		columns: [
			{
				id: "id",
				accessor: "id",
				label: "ID",
				type: "number",
				order: 1,
			},
			{
				id: "name",
				accessor: "name",
				label: "Name",
				type: "string",
				order: 2,
				hasFacetedFilter: true,
			},
			{
				id: "email",
				accessor: "email",
				label: "Email",
				type: "string",
				order: 3,
				hasFacetedFilter: false,
			},
			{
				id: "role",
				accessor: "role",
				label: "Role",
				type: "string",
				order: 4,
				hasFacetedFilter: true,
			},
			{
				id: "active",
				accessor: "active",
				label: "Active",
				type: "boolean",
				order: 5,
				hasFacetedFilter: false,
			},
			{
				id: "createdAt",
				accessor: "createdAt",
				label: "Created At",
				type: "date",
				order: 6,
				hasFacetedFilter: false,
			},
		],
		sampleData: [
			{
				id: 1,
				name: "John Doe",
				email: "john@example.com",
				role: "Admin",
				active: true,
				createdAt: "2023-01-15",
			},
			{
				id: 2,
				name: "Jane Smith",
				email: "jane@example.com",
				role: "User",
				active: true,
				createdAt: "2023-02-20",
			},
			{
				id: 3,
				name: "Bob Johnson",
				email: "bob@example.com",
				role: "Moderator",
				active: false,
				createdAt: "2023-03-10",
			},
		],
	},
	productTable: {
		name: "Product Catalog",
		description: "A table for managing products with pricing and inventory",
		columns: [
			{
				id: "id",
				accessor: "id",
				label: "Product ID",
				type: "number",
				order: 1,
				hasFacetedFilter: false,
			},
			{
				id: "name",
				accessor: "name",
				label: "Product Name",
				type: "string",
				order: 2,
				hasFacetedFilter: true,
			},
			{
				id: "category",
				accessor: "category",
				label: "Category",
				type: "string",
				order: 3,
				hasFacetedFilter: true,
			},
			{
				id: "price",
				accessor: "price",
				label: "Price",
				type: "number",
				order: 4,
				hasFacetedFilter: false,
			},
			{
				id: "stock",
				accessor: "stock",
				label: "Stock",
				type: "number",
				order: 5,
				hasFacetedFilter: false,
			},
			{
				id: "available",
				accessor: "available",
				label: "Available",
				type: "boolean",
				order: 6,
				hasFacetedFilter: false,
			},
		],
		sampleData: [
			{
				id: 1,
				name: "Laptop Pro",
				category: "Electronics",
				price: 1299.99,
				stock: 50,
				available: true,
			},
			{
				id: 2,
				name: "Wireless Mouse",
				category: "Accessories",
				price: 29.99,
				stock: 200,
				available: true,
			},
			{
				id: 3,
				name: "Office Chair",
				category: "Furniture",
				price: 199.99,
				stock: 0,
				available: false,
			},
		],
	},
	orderTable: {
		name: "Order Management",
		description: "A table for tracking customer orders and their status",
		columns: [
			{
				id: "orderId",
				accessor: "orderId",
				label: "Order ID",
				type: "string",
				order: 1,
				hasFacetedFilter: false,
			},
			{
				id: "customerName",
				accessor: "customerName",
				label: "Customer Name",
				type: "string",
				order: 2,
				hasFacetedFilter: true,
			},
			{
				id: "total",
				accessor: "total",
				label: "Total Amount",
				type: "number",
				order: 3,
				hasFacetedFilter: false,
			},
			{
				id: "status",
				accessor: "status",
				label: "Status",
				type: "string",
				order: 4,
				hasFacetedFilter: true,
			},
			{
				id: "orderDate",
				accessor: "orderDate",
				label: "Order Date",
				type: "date",
				order: 5,
				hasFacetedFilter: false,
			},
			{
				id: "shipped",
				accessor: "shipped",
				label: "Shipped",
				type: "boolean",
				order: 6,
				hasFacetedFilter: false,
			},
		],
		sampleData: [
			{
				orderId: "ORD-001",
				customerName: "Alice Brown",
				total: 149.99,
				status: "Processing",
				orderDate: "2023-10-01",
				shipped: false,
			},
			{
				orderId: "ORD-002",
				customerName: "Charlie Wilson",
				total: 299.99,
				status: "Shipped",
				orderDate: "2023-09-28",
				shipped: true,
			},
			{
				orderId: "ORD-003",
				customerName: "Diana Prince",
				total: 79.99,
				status: "Delivered",
				orderDate: "2023-09-25",
				shipped: true,
			},
		],
	},
	taskTable: {
		name: "Task Tracker",
		description: "A table for managing tasks and project progress",
		columns: [
			{
				id: "id",
				accessor: "id",
				label: "Task ID",
				type: "number",
				order: 1,
				hasFacetedFilter: false,
			},
			{
				id: "title",
				accessor: "title",
				label: "Task Title",
				type: "string",
				order: 2,
				hasFacetedFilter: false,
			},
			{
				id: "priority",
				accessor: "priority",
				label: "Priority",
				type: "string",
				order: 3,
				hasFacetedFilter: true,
			},
			{
				id: "assignedTo",
				accessor: "assignedTo",
				label: "Assigned To",
				type: "string",
				order: 4,
				hasFacetedFilter: true,
			},
			{
				id: "dueDate",
				accessor: "dueDate",
				label: "Due Date",
				type: "date",
				order: 5,
				hasFacetedFilter: false,
			},
			{
				id: "completed",
				accessor: "completed",
				label: "Completed",
				type: "boolean",
				order: 6,
				hasFacetedFilter: false,
			},
		],
		sampleData: [
			{
				id: 1,
				title: "Design new homepage",
				priority: "High",
				assignedTo: "Sarah",
				dueDate: "2023-10-15",
				completed: false,
			},
			{
				id: 2,
				title: "Fix login bug",
				priority: "Medium",
				assignedTo: "Mike",
				dueDate: "2023-10-10",
				completed: true,
			},
			{
				id: 3,
				title: "Update documentation",
				priority: "Low",
				assignedTo: "Emma",
				dueDate: "2023-10-20",
				completed: false,
			},
		],
	},
	inventoryTable: {
		name: "Inventory Management",
		description: "A table for tracking inventory levels and suppliers",
		columns: [
			{
				id: "itemCode",
				accessor: "itemCode",
				label: "Item Code",
				type: "string",
				order: 1,
				hasFacetedFilter: false,
			},
			{
				id: "itemName",
				accessor: "itemName",
				label: "Item Name",
				type: "string",
				order: 2,
				hasFacetedFilter: true,
			},
			{
				id: "supplier",
				accessor: "supplier",
				label: "Supplier",
				type: "string",
				order: 3,
				hasFacetedFilter: true,
			},
			{
				id: "quantity",
				accessor: "quantity",
				label: "Quantity",
				type: "number",
				order: 4,
				hasFacetedFilter: false,
			},
			{
				id: "unitCost",
				accessor: "unitCost",
				label: "Unit Cost",
				type: "number",
				order: 5,
				hasFacetedFilter: false,
			},
			{
				id: "lastRestocked",
				accessor: "lastRestocked",
				label: "Last Restocked",
				type: "date",
				order: 6,
				hasFacetedFilter: false,
			},
		],
		sampleData: [
			{
				itemCode: "ITM-001",
				itemName: "Widget A",
				supplier: "Supplier Inc.",
				quantity: 150,
				unitCost: 12.5,
				lastRestocked: "2023-09-15",
			},
			{
				itemCode: "ITM-002",
				itemName: "Gadget B",
				supplier: "Parts Co.",
				quantity: 75,
				unitCost: 25.0,
				lastRestocked: "2023-09-20",
			},
			{
				itemCode: "ITM-003",
				itemName: "Tool C",
				supplier: "Tools Ltd.",
				quantity: 30,
				unitCost: 45.99,
				lastRestocked: "2023-09-10",
			},
		],
	},
};
